<a href="https://colab.research.google.com/github/Isha0711/PyTorch-for-Deep-Learning/blob/main/updated_intro_to_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
- popular research deep learning framework
- write fast deep learning codes in python
- aids transfer learning
- whole stack: pre processes data, model data, deploy model in your application/cloud

In [1]:
print("Hello I am excited to learn PyTorch!")

Hello I am excited to learn PyTorch!


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


##Introduction to tensors

###Creating sensors

PyTorch tensors are created using 'torch.Tensor()'


In [3]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX= torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

##Random tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjus those random numbers to better represent the data.

'start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers




In [13]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7493, 0.1738, 0.8018, 0.5527],
        [0.4680, 0.7473, 0.6638, 0.7822],
        [0.5910, 0.7466, 0.5637, 0.2114]])

In [14]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(3,224,224)) #color channels (R,G,B), height,width,color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [15]:
torch.rand(size=(3,3))

tensor([[0.6095, 0.5030, 0.8306],
        [0.8961, 0.7066, 0.9412],
        [0.4287, 0.6686, 0.8839]])

##Zeros and Ones


In [16]:
#create a tensor of all zeroes
zeros = torch.zeros(size = (3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
#create a tensor of all ones
ones= torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like



In [19]:
#use torch.range()
one_to_ten=torch.arange(start=0,end=1000,step=100)
one_to_ten

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [20]:
#creating tensors like
ten_zeroes= torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes
Default=torch.float32
(also called single precision floating point)
Most commonly used is 32 and 16-bit floating point(also called half precision floating point.it is less precise but fast)



In [21]:
#Float 32 tensor for default case
float_32_tensor= torch.tensor([3.0,6.0,9.0])
float_32_tensor

tensor([3., 6., 9.])

Tensor datatypes can include errors due to:
- Not right datatype
- Not right shape
- Not on the right device

In [22]:
#Float 32 tensor
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=None, #what datatype is the tensor
                              device=None, #by default is CPU, could be gpu(cuda)too
                              requires_grad=False #whether or not to track gradients with this tensor operation
                              )

float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
#converting float 32 tensor to float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor.dtype

torch.float16

#Getting information from tensors(Tensor attributes)

- Not right datatype:  to get the datatype from a tensor, use 'tensor.dtype'
- Not right shape - to get shape from a tensor, use 'tensor.shape'
- Not on the right device - to get device from a tensor, use 'tensor.device'

In [28]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5311, 0.4622, 0.7642, 0.1219],
        [0.3934, 0.0618, 0.2753, 0.0276],
        [0.1928, 0.2297, 0.1635, 0.1449]])

In [29]:
#to find details of the tensor above
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device the tensor is on: {some_tensor.device}")

tensor([[0.5311, 0.4622, 0.7642, 0.1219],
        [0.3934, 0.0618, 0.2753, 0.0276],
        [0.1928, 0.2297, 0.1635, 0.1449]])
Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device the tensor is on: cpu




##Manipulating Tensors
Tensor operations include:
- Addition
- subtraction
- multiplication(element wise)
- division
- matrix multiplication



In [30]:
#create a tensor and add
tensor= torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
#multiply
tensor = tensor *10
tensor

tensor([10, 20, 30])

In [32]:
#divison
tensor/10

tensor([1., 2., 3.])

In [33]:
#using in-built functions
torch.mul(tensor,10)
torch.add(tensor,10)



tensor([20, 30, 40])

#Matrix Multiplication
rules:

- Inner dimension must match

. (3,2) @ (3,2) wont work

. (2,3) @ (3,2) will work

. (3,2) @ (2,3) will work

- Resulting matrix has the shape of the outer dimension

.  (2,3) @ (3,2) -> (2,2)

.  (3,2) @ (2, 3) -> (3,3)

In [34]:
#element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [35]:
#matrix multiplication
torch.matmul(tensor,tensor) #recommended
# tensor @ tensor , can be used instead

tensor(1400)

In [36]:
 torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.6330, 3.2939, 2.3831],
        [0.9242, 1.7996, 0.7586],
        [2.3743, 1.6566, 1.3308]])

In [42]:
#to fix shape issue, we transpose one matrix
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
tensor_a, tensor_b, tensor_b.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [43]:
print(f"Original shapes: tensor_a = {tensor_a.shape}, tensor_b= {tensor_b.shape}")
print(f"New shapes: tensor_a = {tensor_a.shape}, tensor_b.T= {tensor_b.T.shape}")
print(f"Multiplying: {tensor_a.shape} @ {tensor_b.T.shape}")
print("\nOutput:\n")
output = torch.mm(tensor_a, tensor_b.T)
print(output)
print(f"Output shape= {output.shape}")



Original shapes: tensor_a = torch.Size([3, 2]), tensor_b= torch.Size([3, 2])
New shapes: tensor_a = torch.Size([3, 2]), tensor_b.T= torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape= torch.Size([3, 3])


##Tensor aggregation
Finding min,max, mean, sum,etc

In [44]:
#create a tensor
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [45]:
#min
#torch.min(x)
x.min()

tensor(1)

In [46]:
#max
torch.max(x)
#x.max()

tensor(91)

In [47]:
#mean: the function requirres a tensor of float32 datatype instead of long
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [48]:
#sum
torch.sum(x) , x.sum()


(tensor(460), tensor(460))

In [49]:
#positional min max
x.argmin(), x.argmax() #find the position in tensor that has
                       #the minimum value->returns index position

(tensor(0), tensor(9))

In [50]:
x[0], x[9]

(tensor(1), tensor(91))

#reshaping, stacking, squeezing and unsqeezing tensors
* reshaping: reshape an input tensor to a defined shape
* view: return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking: combine multiple tensors on top of each other(vstack) or side by side (hstack)  
* squeeze: removes all '1' dimensions from a tensor
* unsqueeze: add a '1' dimension to a target tensor
* permute: return a view of the input with dimensions permuted (swapped) in a certain way

In [51]:
#create a tensor
y= torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
#add an extra dimension
y_reshaped= y.reshape(1,9) #9 *1 =9 i.e the size of the tensor
y_reshaped , y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
#change the view
z=y.view(1,9) #z is just another view of y as view of a tensor
              #shares the same memory as the original input
              #changes in z changes y
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
#stack tensors on top of eachother
y_stacked= torch.stack([y,y,y,y],dim=0)
y_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
#torch.squeeze() that removes all single dimension from a target tensor
print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape: {y_reshaped.shape}")
y_squeezed = y_reshaped.squeeze()

print(f"New tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [56]:
#torch.unsqueeze()
print(f"Previous tensor: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")
y_unsqueezed = y_squeezed.unsqueeze(dim=0)

print(f"New tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [57]:
#torch.permute
y_original = torch.rand(size=(224,224,3)) #height,width, colour_channels
y_original
#permute
y_permuted= y_original.permute(2,0,1)
y_permuted

tensor([[[0.4860, 0.1862, 0.5548,  ..., 0.5725, 0.8768, 0.8802],
         [0.5526, 0.7170, 0.2032,  ..., 0.5840, 0.7539, 0.4682],
         [0.5864, 0.2474, 0.1152,  ..., 0.9411, 0.4117, 0.2716],
         ...,
         [0.6690, 0.1639, 0.5383,  ..., 0.7779, 0.5287, 0.8859],
         [0.8642, 0.8138, 0.4060,  ..., 0.8698, 0.3991, 0.3829],
         [0.3932, 0.0855, 0.3979,  ..., 0.6141, 0.4160, 0.2397]],

        [[0.6699, 0.2591, 0.2270,  ..., 0.6058, 0.5165, 0.7830],
         [0.6373, 0.0673, 0.6765,  ..., 0.2701, 0.2143, 0.8663],
         [0.7441, 0.3418, 0.8325,  ..., 0.7188, 0.9090, 0.8773],
         ...,
         [0.9680, 0.9341, 0.0407,  ..., 0.8163, 0.7391, 0.5898],
         [0.5001, 0.1737, 0.1323,  ..., 0.8327, 0.6826, 0.5200],
         [0.7135, 0.6660, 0.1065,  ..., 0.9201, 0.3426, 0.9798]],

        [[0.1172, 0.5763, 0.3615,  ..., 0.9706, 0.9774, 0.1879],
         [0.9433, 0.9957, 0.7245,  ..., 0.2815, 0.3111, 0.1040],
         [0.8655, 0.8977, 0.5483,  ..., 0.7962, 0.5672, 0.

#Indexing (selecting data from tensors)


In [58]:
#create a tensor
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
#index on our new tensor
x[0], x[0][0], x[0][0][0] #x[1][0][0] can't be used as the dimension is 1,3,3

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

try different ways of indexing on your own

##PyTorch tensors and NumPy

Numpy is a popular scientific Python numerical computing library


In [60]:
#NumPy array to tensor
import torch
import numpy as np

array= np.arange(1.0,8.0)
tensor= torch.from_numpy(array) #default datatype float64 when converting from numpy
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [61]:
#change the value of array, effect on tensor
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

thus, no change



In [62]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility (trying to take random out of random)

 to reduce randomness in neural networks, pytorch comes with the concpet of a **random seed**.
 It flavours the randomness.

In [63]:

import torch

#set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##running tensors and pytorch objects on the GPUS ( and making faster computations)

In [64]:
##check for GPU access with PyTorch
import torch
torch.cuda.is_available()


True

In [65]:
#setup device agnostic code (best practice)
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [66]:
#count number of devices
torch.cuda.device_count()

1

In [67]:
#putting tensors (and models) on the GPU (for faster computations)
tensor= torch.tensor([1,2,3])
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [68]:
#move tensor to gpu (if available)
tensor_on_gpu= tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [69]:
## moving tensors back to cpu
#if tensor is on gpu, can't transform it to numpy
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [70]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Exercises for practice:


In [71]:
##create a random tensor of shape(7,7)
import torch
tensor1= torch.rand(7,7)
tensor1

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [72]:
#matrix multiplication
tensor2= torch.rand(1,7)
tensor= tensor1 @ tensor2.T
tensor

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [73]:
torch.manual_seed(0)
tensor1= torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor2= torch.rand(1,7)
tensor = tensor1 @ tensor2.T
tensor, tensor.shape

(tensor([[1.9281],
         [1.9982],
         [2.1757],
         [2.7055],
         [1.7855],
         [1.9367],
         [1.6980]]),
 torch.Size([7, 1]))

In [74]:
#set random seed on GPU
torch.cuda.manual_seed(1234)

In [75]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
#Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)
torch.manual_seed(1234)

device= "cuda" if torch.cuda.is_available() else print(f"Device = {device}")
tensor_A= torch.rand(2,3).to(device)
tensor_B= torch.rand(2,3).to(device)
tensor_A, tensor_B


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [76]:
#matrix multiplication of the tensors created above

tensor= tensor_A @ tensor_B.T
tensor_A.shape, tensor_B.shape, tensor

(torch.Size([2, 3]),
 torch.Size([2, 3]),
 tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'))

In [77]:
#min max of above output
tensor.max(), tensor.min()


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [78]:
#min max index values of above output
tensor.argmax(), tensor.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [79]:
#Make a random tensor with shape (1, 1, 1, 10) and then
#create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
#Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
tensor_a= torch.rand(1,1,1,10)
tensor_b= tensor_a.squeeze()
tensor_a,tensor_a.shape, tensor_b, tensor_b.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))